M48
; DRILL file {KiCad 8.0.8} date 2025-07-04T19:36:45+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-04T19:36:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X162.595Y-50.01
X162.595Y-55.79
T2
X112.95Y-63.55
X164.388Y-43.3
X164.4Y-83.8
M30
